# Use the official Python 3.9 base image
FROM python:3.9

# Copy the hello.txt file into the root directory of the image
COPY hello.txt /

# When the container starts, cat the hello.txt file
CMD ["cat", "hello.txt"]
